### ISSUE TITLE
ISGeneralDebug and IsoRegionsWindow - open after post-death new character creation

### ISSUE THREAD

**Issue by ChuckTheSheep** [ChuckTheSheep/pz-community-modding#20]

**Comment by Poltergeistzx** [comment]
Can you explain more, it works fine in vanilla. With debug enabled it errors out.

**Comment by ChuckTheSheep** [comment]
Currently working in dev branch.
After one dies, regardless if the windows are open on death or not, those 2 windows specifically open.
